version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  alimentar:
    build: './alimentar_nums'
    depends_on:
      - redis
    volumes:
      - ./alimentar_nums:/code
    command: python alimentar.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      
  calc-a:
    build: './calcular_nums'
    depends_on:
      - redis
    volumes:
      - ./calcular_nums:/code
    command: python calcular.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis      

  calc-b:
    build: './calcular_nums'
    depends_on:
      - redis
    volumes:
      - ./calcular_nums:/code
    command: python calcular.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  calc-c:
    build: './calcular_nums'
    depends_on:
      - redis
    volumes:
      - ./calcular_nums:/code
    command: python calcular.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis  

  calc-d:
    build: './calcular_nums'
    depends_on:
      - redis
    volumes:
      - ./calcular_nums:/code
    command: python calcular.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis  